### ISSUE TITLE
Improvements v2

### ISSUE THREAD

**Issue by tushar5526** [samagra-comms/docker-deploy#23]
Fix: 
- [x] Vault needed for UCI (to be added in docker compose) https://github.com/samagra-comms/docker-deploy/pull/34
- [x] Run prisma migrations in UCI for fresh installs https://github.com/samagra-comms/uci-apis/pull/60
- [x] No Dockerfile in uci-api-v2 https://github.com/samagra-comms/uci-apis/pull/60
- [x] Fix networks in docker compose for services. https://github.com/samagra-comms/docker-deploy/pull/34
- [x] Fix UCI admin Dockerfile https://github.com/samagra-comms/uci-admin/pull/18
- [x] Document manual steps https://github.com/samagra-comms/docker-deploy/pull/34
- [x] Add missing env vars https://github.com/samagra-comms/docker-deploy/pull/34
- [ ] Add more details in manual steps or automate them in install script
 
Enhancements
---------------------------
- [x] Identify and un-expose ports of service that are not required over the internet #49
- [x] Fusionauth forms-db-gql admin key was written directly in compose #38  
- [x] Some data in docker volumes and some in folder (everything should be in folders to prevent accidental removal of prod data volumes) #43 
- [x] FusionAuth Application Setup using Kickstart
- [x] It seems only one redis is being used, check this and remove extra caches.
- [x] https://github.com/samagra-comms/transformer/blob/master/src/main/resources/application.properties - make doubtnut optional
- [x] Some secrets are hardcoded in docker-compose. Have to be moved to env. 
- [x] Rename services for better understanding. Cache should not be named as `db`. Service owners can clarify here.
- [x] Cassandra password is not being picked from .env 
- [x] Ask for `github` token that has read access to packages in install script after cloning uci-apis #47 
- [x] Minio needed for UCI (to be added in docker compose) https://github.com/Samagra-Development/minio-oauth2-docs
- [ ] Automatically change ODK password
- [ ] env_file is mapped to .env directly and all secrets available in each service. #33 
- [ ] Prefill the adapters, conversation-logic, bot tables so there is a bot out of the box.

Good to have
-----------------
- [ ] Fix the `VAULT_` variable name - https://github.com/samagra-comms/utils/issues/34
- [ ] Using sample.env and generating a .env using some script. #22 
- [ ] AKHQ username password is written directly to compose. Also test it so that its not available to internet. #37 
- [ ] Optimise dockerfiles
- [ ] Add `docker-compose-swarm.yml` and `db-compose` from Dockerswarm servers for users who want to deploy it as a swarm. stateless and stateful services are already segregated.

**Comment by ChakshuGautam** [comment]
Actual env files that are required by every service 
1. [Orchestrator](https://github.com/project-sunbird/sunbird-devops/blob/release-5.1.0/ansible/roles/stack-sunbird/templates/orchestrator.env)
2. [Transformer](https://github.com/project-sunbird/sunbird-devops/blob/release-5.1.0/ansible/roles/stack-sunbird/templates/transformer.env)

**Comment by karntrehan** [comment]
Anvansh to pick up enhancements.

**Comment by RyanWalker277** [comment]
Marking the enhancements for which I have created a PR here. Still unable to link issues and PRs to the original checklist.

- [ ] Fusionauth forms-db-gql admin key was written directly in compose https://github.com/samagra-comms/docker-deploy/pull/38
- [ ] AKHQ username password is written directly to compose. Also test it so that its not available to internet. https://github.com/samagra-comms/docker-deploy/pull/39
- [ ] Some data in docker volumes and some in folder (everything should be in folders to prevent accidental removal of prod data volumes) https://github.com/samagra-comms/docker-deploy/pull/43
- [ ] It seems only one redis is being used, check this and remove extra caches. https://github.com/samagra-comms/docker-deploy/pull/45

**Comment by susheelvar** [comment]
@tushar5526 to review these PRs and merging.

**Comment by susheelvar** [comment]
Previous PRs merged by @tushar5526 

@RyanWalker277 to raise 1 PR today.

**Comment by RyanWalker277** [comment]
> Previous PRs merged by @tushar5526
> 
> @RyanWalker277 to raise 1 PR today.

Raised the PR yesterday, synced dev with main and also completed work on some existing PRs and got them merged. Currently working on #58, since I am not that familiar with ODK, it might take a while to figure out the exact cause of the issue, will talk to @pankajjangid05 to figure out exact issue. Had a talk with yesterday with @tushar5526 and @chinmoy12c regarding the same.

**Comment by RyanWalker277** [comment]
There are 3 containers related to ODK, namely 
aggregate-server :  a tomcat container running odk
aggregate-db : postgres image
wait-for-db : waits for db to be up

The the aggregate-db container works fine. I can log in with the same creds as given in `.env`
![image](https://github.com/samagra-comms/docker-deploy/assets/32684077/f64b543f-2766-416b-8293-e9d5921b7ba2)
Unable to replicate the issue at my end till now. Will look a bit deeper to replicate and solve this . Also, reached out to @pankajjangid05 on discord yesterday. Awaiting a response as of now

cc- @karntrehan @susheelvar

**Comment by RyanWalker277** [comment]
Had a talk with @tushar5526, the issue is with the aggregate-server, admin creds are not picked up from .env. Looking into it. Will send a patch soon.

**Comment by RyanWalker277** [comment]
PR raised on odk (https://github.com/samagra-comms/odk/pull/6) for #58.

**Comment by karntrehan** [comment]
Improvements are almost closed. @RyanWalker277 to present macro wins with these changes.
